add path to intro notebook
MonashBI/nipype_arcana_workshop pull request #2
Opened 2019-10-28 07:11 UTC by orchid00

2019-10-29 23:52 UTC, tclose requested changes
Hi Paula,

I have made some comments on your proposed changes.

Cheers,

Tom

2019-10-29 23:52 UTC, tclose commented on slides/background_python_and_jupyter_notebook.html
> +      - We recommend [Jupyter notebook](https://jupyter.org/)
Jupyter notebooks are not technically "terminal and text editor" and they are introduced below. I would like to leave this as it was

2019-10-29 23:52 UTC, tclose commented on slides/background_python_and_jupyter_notebook.html
> +Please go to the folder `project/notebooks/` and type in the console [`jupyter notebook introduction_jupyter-notebook.ipynb`](../../notebooks/notebooks/introduction_jupyter-notebook.ipynb) now
They don't need to go to the console as they should be able to just click on the link.

2019-10-29 23:52 UTC, tclose commented on slides/background_python_and_jupyter_notebook.html
> +Please go through the [`jupyter notebook introduction_python.ipynb`](../../notebooks/notebooks/introduction_python.ipynb) now
The user won't need to know that the file is called 'introduction_python.ipynb' as they can just use the links here and on the program page

2019-10-29 23:52 UTC, tclose commented on slides/background_python_and_jupyter_notebook.html
> +# number of leading spaces is very important!
I think I prefer how I had it before, what is your thinking behind this change?

2019-10-29 23:52 UTC, tclose commented on slides/background_python_and_jupyter_notebook.html
> +## Python - Important to know 1
Should this be "Important to know 2"?

2019-10-30 05:08 UTC, orchid00 commented
@tclose I'll discard the changes,

2019-10-30 05:08 UTC, closed without merging